Repository elastic/ansible-elasticsearch, pull requests merged in 2020-11, with the labels that each got.

#739 fix: small error
  README.md
Labels: enhancement

#741 [meta] clean deprecated bumper script
  helpers/bumper.py
Labels: meta

#742 convert custom filter to python3
  filter_plugins/custom.py
Labels: meta

#736 Fix test-kitchen net-scp-error
  .kitchen.yml
Labels: meta

#744 Support CentOS 8
  .kitchen.yml
  README.md
  test/matrix.yml
Labels: feature request
